INSERT INTO players (name) values ('Ethan Caldwell');
INSERT INTO players (name) values ('Olivia Bennett');
INSERT INTO players (name) values ('Lucas Moretti');
INSERT INTO players (name) values ('Sofia Navarro');
INSERT INTO players (name) values ('Daniel Whitaker');
INSERT INTO players (name) values ('Ethan Spencer');
INSERT INTO players (name) values ('Olivia Carter');
INSERT INTO players (name) values ('Mason Bradley');
INSERT INTO players (name) values ('Zoe Mitchell');
INSERT INTO players (name) values ('Lucas Bennett');
INSERT INTO players (name) values ('Harper Reed');
INSERT INTO players (name) values ('Isaac Holland');
INSERT INTO players (name) values ('Ruby Miles');
INSERT INTO players (name) values ('Noah Preston');
INSERT INTO players (name) values ('Mia Chambers');

INSERT INTO matches (player1, player2, winner) values ('2', '5', '2');
INSERT INTO matches (player1, player2, winner) values ('1', '3', '3');
INSERT INTO matches (player1, player2, winner) values ('1', '2', '1');
INSERT INTO matches (player1, player2, winner) values ('5', '4', '5');
INSERT INTO matches (player1, player2, winner) values ('4', '3', '4');
INSERT INTO matches (player1, player2, winner) values ('3', '8', '8');
INSERT INTO matches (player1, player2, winner) values ('12', '4', '4');
INSERT INTO matches (player1, player2, winner) values ('9', '15', '9');
INSERT INTO matches (player1, player2, winner) values ('8', '6', '6');
INSERT INTO matches (player1, player2, winner) values ('3', '10', '10');
INSERT INTO matches (player1, player2, winner) values ('11', '12', '11');
INSERT INTO matches (player1, player2, winner) values ('5', '7', '5');
INSERT INTO matches (player1, player2, winner) values ('13', '14', '13');
INSERT INTO matches (player1, player2, winner) values ('3', '9', '9');
INSERT INTO matches (player1, player2, winner) values ('12', '15', '15');